import {
  Combine,
  Scissors,
  FileDown,
  FileText,
  FileType,
  Image,
  ImagePlus,
  RotateCw,
  Lock,
  Stamp,
  LucideIcon,
  Unlock,
  BookOpen,
  FileSearch,
  GripVertical,
  FileOutput,
  FileCode,
  Tags,
  Eraser,
  Eye,
  Crown,
  Table2,
  FileSpreadsheet,
  PenTool,
  Hash,
  Layers,
  Wrench,
  Square,
  MessageSquare,
} from 'lucide-react';
import { ToolDef } from '@/components/toolpdf/ToolCard';

export type ToolTier = 'free' | 'premium';

export interface ToolDefExtended extends ToolDef {
  tier: ToolTier;
  isNew?: boolean;
}

export const tools: ToolDefExtended[] = [
  // === ORGANIZE ===
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one document',
    icon: Combine,
    gradient: 'from-emerald-500 to-cyan-500',
    iconBg: 'linear-gradient(135deg, rgba(16,185,129,0.2), rgba(6,182,212,0.2))',
    category: 'organize',
    tier: 'free',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Extract or split pages from any PDF',
    icon: Scissors,
    gradient: 'from-cyan-500 to-teal-500',
    iconBg: 'linear-gradient(135deg, rgba(6,182,212,0.2), rgba(20,184,166,0.2))',
    category: 'organize',
    tier: 'free',
  },
  {
    id: 'extract-pages',
    name: 'Extract Pages',
    description: 'Extract specific pages from a PDF into a new file',
    icon: FileSearch,
    gradient: 'from-teal-500 to-emerald-500',
    iconBg: 'linear-gradient(135deg, rgba(20,184,166,0.2), rgba(16,185,129,0.2))',
    category: 'organize',
    tier: 'free',
  },
  {
    id: 'reorder-pages',
    name: 'Reorder Pages',
    description: 'Drag and drop to rearrange PDF page order',
    icon: GripVertical,
    gradient: 'from-green-500 to-lime-500',
    iconBg: 'linear-gradient(135deg, rgba(34,197,94,0.2), rgba(132,204,22,0.2))',
    category: 'organize',
    tier: 'free',
  },

  // === OPTIMIZE ===
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce PDF file size without losing quality',
    icon: FileDown,
    gradient: 'from-amber-500 to-orange-500',
    iconBg: 'linear-gradient(135deg, rgba(245,158,11,0.2), rgba(249,115,22,0.2))',
    category: 'optimize',
    tier: 'free',
  },
  {
    id: 'flatten-pdf',
    name: 'Flatten PDF',
    description: 'Flatten PDF forms and annotations into static content',
    icon: Layers,
    gradient: 'from-orange-500 to-yellow-500',
    iconBg: 'linear-gradient(135deg, rgba(249,115,22,0.2), rgba(234,179,8,0.2))',
    category: 'optimize',
    tier: 'premium',
    isNew: true,
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    description: 'Repair corrupted or damaged PDF files',
    icon: Wrench,
    gradient: 'from-yellow-500 to-amber-500',
    iconBg: 'linear-gradient(135deg, rgba(234,179,8,0.2), rgba(245,158,11,0.2))',
    category: 'optimize',
    tier: 'free',
    isNew: true,
  },

  // === CONVERT ===
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF to editable Word document',
    icon: FileText,
    gradient: 'from-violet-500 to-purple-500',
    iconBg: 'linear-gradient(135deg, rgba(139,92,246,0.2), rgba(168,85,247,0.2))',
    category: 'convert',
    tier: 'free',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents to PDF format',
    icon: FileType,
    gradient: 'from-purple-500 to-pink-500',
    iconBg: 'linear-gradient(135deg, rgba(168,85,247,0.2), rgba(236,72,153,0.2))',
    category: 'convert',
    tier: 'free',
  },
  {
    id: 'pdf-to-image',
    name: 'PDF to Image',
    description: 'Convert PDF pages to high-quality images',
    icon: Image,
    gradient: 'from-rose-500 to-red-500',
    iconBg: 'linear-gradient(135deg, rgba(244,63,94,0.2), rgba(239,68,68,0.2))',
    category: 'convert',
    tier: 'free',
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert images to PDF document',
    icon: ImagePlus,
    gradient: 'from-orange-500 to-amber-500',
    iconBg: 'linear-gradient(135deg, rgba(249,115,22,0.2), rgba(245,158,11,0.2))',
    category: 'convert',
    tier: 'free',
  },
  {
    id: 'pdf-to-html',
    name: 'PDF to HTML',
    description: 'Convert PDF content to HTML format for web publishing',
    icon: FileCode,
    gradient: 'from-sky-500 to-blue-500',
    iconBg: 'linear-gradient(135deg, rgba(14,165,233,0.2), rgba(59,130,246,0.2))',
    category: 'convert',
    tier: 'premium',
    isNew: true,
  },
  {
    id: 'convert-to-pdf',
    name: 'Convert to PDF',
    description: 'Convert any file (Excel, PPT, TXT, CSV) to PDF format',
    icon: FileOutput,
    gradient: 'from-indigo-500 to-violet-500',
    iconBg: 'linear-gradient(135deg, rgba(99,102,241,0.2), rgba(139,92,246,0.2))',
    category: 'convert',
    tier: 'premium',
    isNew: true,
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Convert PDF tables to Excel spreadsheets',
    icon: Table2,
    gradient: 'from-emerald-500 to-teal-500',
    iconBg: 'linear-gradient(135deg, rgba(16,185,129,0.2), rgba(20,184,166,0.2))',
    category: 'convert',
    tier: 'premium',
    isNew: true,
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF',
    icon: FileSpreadsheet,
    gradient: 'from-teal-500 to-cyan-500',
    iconBg: 'linear-gradient(135deg, rgba(20,184,166,0.2), rgba(6,182,212,0.2))',
    category: 'convert',
    tier: 'free',
    isNew: true,
  },

  // === EDIT ===
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages to any orientation',
    icon: RotateCw,
    gradient: 'from-teal-500 to-green-500',
    iconBg: 'linear-gradient(135deg, rgba(20,184,166,0.2), rgba(34,197,94,0.2))',
    category: 'edit',
    tier: 'free',
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    description: 'Add custom text watermarks to PDF pages',
    icon: Stamp,
    gradient: 'from-violet-500 to-cyan-500',
    iconBg: 'linear-gradient(135deg, rgba(139,92,246,0.2), rgba(6,182,212,0.2))',
    category: 'edit',
    tier: 'free',
  },
  {
    id: 'remove-watermark',
    name: 'Remove Watermark',
    description: 'Remove text watermarks from PDF documents',
    icon: Eraser,
    gradient: 'from-yellow-500 to-amber-500',
    iconBg: 'linear-gradient(135deg, rgba(234,179,8,0.2), rgba(245,158,11,0.2))',
    category: 'edit',
    tier: 'premium',
    isNew: true,
  },
  {
    id: 'edit-metadata',
    name: 'Edit PDF Metadata',
    description: 'View and edit PDF title, author, subject, and keywords',
    icon: Tags,
    gradient: 'from-pink-500 to-rose-500',
    iconBg: 'linear-gradient(135deg, rgba(236,72,153,0.2), rgba(244,63,94,0.2))',
    category: 'edit',
    tier: 'free',
    isNew: true,
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Add digital signature to PDF documents',
    icon: PenTool,
    gradient: 'from-blue-500 to-indigo-500',
    iconBg: 'linear-gradient(135deg, rgba(59,130,246,0.2), rgba(99,102,241,0.2))',
    category: 'edit',
    tier: 'premium',
    isNew: true,
  },
  {
    id: 'number-pages',
    name: 'Number Pages',
    description: 'Add page numbers to PDF',
    icon: Hash,
    gradient: 'from-slate-500 to-gray-500',
    iconBg: 'linear-gradient(135deg, rgba(100,116,139,0.2), rgba(156,163,175,0.2))',
    category: 'edit',
    tier: 'free',
    isNew: true,
  },
  {
    id: 'annotate-pdf',
    name: 'Annotate PDF',
    description: 'Add comments and annotations to PDF',
    icon: MessageSquare,
    gradient: 'from-fuchsia-500 to-purple-500',
    iconBg: 'linear-gradient(135deg, rgba(192,132,252,0.2), rgba(168,85,247,0.2))',
    category: 'edit',
    tier: 'free',
    isNew: true,
  },

  // === SECURITY ===
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Add password protection to your PDF',
    icon: Lock,
    gradient: 'from-red-500 to-rose-500',
    iconBg: 'linear-gradient(135deg, rgba(239,68,68,0.2), rgba(244,63,94,0.2))',
    category: 'security',
    tier: 'free',
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password protection from encrypted PDF files',
    icon: Unlock,
    gradient: 'from-emerald-500 to-violet-500',
    iconBg: 'linear-gradient(135deg, rgba(16,185,129,0.2), rgba(139,92,246,0.2))',
    category: 'security',
    tier: 'premium',
    isNew: true,
  },
  {
    id: 'redact-pdf',
    name: 'Redact PDF',
    description: 'Redact sensitive text from PDF',
    icon: Square,
    gradient: 'from-neutral-500 to-zinc-500',
    iconBg: 'linear-gradient(135deg, rgba(113,113,122,0.2), rgba(161,161,170,0.2))',
    category: 'security',
    tier: 'premium',
    isNew: true,
  },

  // === FILE READING ===
  {
    id: 'file-reader',
    name: 'File Reader',
    description: 'Read and preview any file type — text, code, spreadsheets, presentations & more',
    icon: BookOpen,
    gradient: 'from-cyan-500 to-blue-500',
    iconBg: 'linear-gradient(135deg, rgba(6,182,212,0.2), rgba(59,130,246,0.2))',
    category: 'reader',
    tier: 'free',
    isNew: true,
  },
  {
    id: 'view-pdf',
    name: 'View PDF',
    description: 'Preview and read PDF documents directly in your browser',
    icon: Eye,
    gradient: 'from-emerald-500 to-green-500',
    iconBg: 'linear-gradient(135deg, rgba(16,185,129,0.2), rgba(34,197,94,0.2))',
    category: 'reader',
    tier: 'free',
    isNew: true,
  },
];

export const categories = [
  { id: 'organize', name: 'Organize', icon: Combine },
  { id: 'optimize', name: 'Optimize', icon: FileDown },
  { id: 'convert', name: 'Convert', icon: FileText },
  { id: 'edit', name: 'Edit', icon: Stamp },
  { id: 'security', name: 'Security', icon: Lock },
  { id: 'reader', name: 'Read & Preview', icon: BookOpen },
];
