import {
  Combine,
  Scissors,
  FileDown,
  FileText,
  FileType,
  Image,
  ImagePlus,
  RotateCw,
  Lock,
  Stamp,
  Table,
  LucideIcon,
} from 'lucide-react';
import { ToolDef } from '@/components/toolpdf/ToolCard';

export const tools: ToolDef[] = [
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one document',
    icon: Combine,
    gradient: 'from-emerald-500 to-cyan-500',
    iconBg: 'linear-gradient(135deg, rgba(16,185,129,0.2), rgba(6,182,212,0.2))',
    category: 'organize',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Extract or split pages from any PDF',
    icon: Scissors,
    gradient: 'from-cyan-500 to-teal-500',
    iconBg: 'linear-gradient(135deg, rgba(6,182,212,0.2), rgba(20,184,166,0.2))',
    category: 'organize',
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce PDF file size without losing quality',
    icon: FileDown,
    gradient: 'from-amber-500 to-orange-500',
    iconBg: 'linear-gradient(135deg, rgba(245,158,11,0.2), rgba(249,115,22,0.2))',
    category: 'optimize',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF to editable Word document',
    icon: FileText,
    gradient: 'from-violet-500 to-purple-500',
    iconBg: 'linear-gradient(135deg, rgba(139,92,246,0.2), rgba(168,85,247,0.2))',
    category: 'convert',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents to PDF format',
    icon: FileType,
    gradient: 'from-purple-500 to-pink-500',
    iconBg: 'linear-gradient(135deg, rgba(168,85,247,0.2), rgba(236,72,153,0.2))',
    category: 'convert',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF format',
    icon: Table,
    gradient: 'from-green-500 to-emerald-500',
    iconBg: 'linear-gradient(135deg, rgba(34,197,94,0.2), rgba(16,185,129,0.2))',
    category: 'convert',
  },
  {
    id: 'pdf-to-image',
    name: 'PDF to Image',
    description: 'Convert PDF pages to high-quality images',
    icon: Image,
    gradient: 'from-rose-500 to-red-500',
    iconBg: 'linear-gradient(135deg, rgba(244,63,94,0.2), rgba(239,68,68,0.2))',
    category: 'convert',
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert images to PDF document',
    icon: ImagePlus,
    gradient: 'from-orange-500 to-amber-500',
    iconBg: 'linear-gradient(135deg, rgba(249,115,22,0.2), rgba(245,158,11,0.2))',
    category: 'convert',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages to any orientation',
    icon: RotateCw,
    gradient: 'from-teal-500 to-green-500',
    iconBg: 'linear-gradient(135deg, rgba(20,184,166,0.2), rgba(34,197,94,0.2))',
    category: 'edit',
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Add password protection to your PDF',
    icon: Lock,
    gradient: 'from-red-500 to-rose-500',
    iconBg: 'linear-gradient(135deg, rgba(239,68,68,0.2), rgba(244,63,94,0.2))',
    category: 'security',
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    description: 'Add custom text watermarks to PDF pages',
    icon: Stamp,
    gradient: 'from-violet-500 to-cyan-500',
    iconBg: 'linear-gradient(135deg, rgba(139,92,246,0.2), rgba(6,182,212,0.2))',
    category: 'edit',
  },
];